### ISSUE TITLE
Story Creation

### ISSUE THREAD

**Issue by Micha-L-Davis** [Digital-Dinosaur/infinite-landscape-frontend#1]
As a user I want to be able to contribute to the infinite landscape by creating a story.

- [x] Story Submission form #10 
- [x] Form event handlers #11  
- [x] API route to send the story #12
